name: deploy lambda function and api gateway to aws

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: [3.8]

    steps:
      - name: check out repository code
        uses: actions/checkout@v2

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with: 
          python-version: ${{ matrix.python-version }}
          # python-version: "3.x"

      - name: display Python version
        run: python -c "import sys; print(sys.version)"
      
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: run unit tests
        run: pytest tests/unit/*

      - name: setup aws sam cli
        uses: aws-actions/setup-sam@v1
      
      - name: configure with aws credentials and region
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      # sam build 
      - name: build lambda-like docker container
        run: sam build --use-container

      # sam deploy
      - name: deploy sam application to aws
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name VisitorApi --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-1ifcap9cu3w66 --capabilities CAPABILITY_IAM --region us-east-1

      - name: run integration tests
        run: pytest -v tests/integration/*